#
#        docker build -t add-copy-example .
#        docker images
#        docker run add-copy-example cmd.exe /c c:\work\someCommands
#
FROM     mcr.microsoft.com/windows/nanoserver:1809
WORKDIR  C:/work 
COPY     someCommands.bat .
